/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\paris-bis.glb --shadows 
*/

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { RigidBody } from "@react-three/rapier";
// import { useLoader } from "@react-three/fiber";
// import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

// export function Track() {
//     const track = useLoader(GLTFLoader, "../src/assets/3D/track.glb");

//     return (
//         <mesh>
//             <primitive object={track}></primitive>;
//         </mesh>
//     );
// }

// useGLTF.preload("./models/tracks/paris-bis.glb");

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Track(props) {
    const { scene } = useGLTF("../src/assets/3D/racetrack_test.glb");
    return <primitive object={scene} {...props} />;
}
